### PR TITLE
Add publish_gem Github Action

### PR DESCRIPTION
**Pull request by bugloper**
Add publish_gem Github Action

### CODE REVIEW

**Comment by bugloper** [comment]
@excid3 Please check once.

**Comment by excid3** [comment]
@bugloper I didn't know about this Google action.

I was actually thinking we should use Rubygems trusted publishing like we do in Pay. Probably could just copy this over: https://github.com/pay-rails/pay/blob/main/.github/workflows/publish_gem.yml

**Comment by bugloper** [comment]
> https://github.com/pay-rails/pay/blob/main/.github/workflows/publish_gem.yml

Oh, sure. Will add it

**Comment by bugloper** [comment]
At the company I work for currently, we are migration from `wicked_pdf` to `gotenberg`. So, I created this gem called [gotenberg](https://github.com/SELISEdigitalplatforms/gotenberg/). I didn't know about ferrum until now.

**Comment by excid3** [comment]
I saw gotenberg mentioned in a GitHub Issue earlier. Looks like a great project!

**Pull request merged**
